### ISSUE TITLE
Integrate 5-AdvancedTopics/time-aggregation.ipynb into 18-defining-time-periods.ipynb

### ISSUE THREAD

**Issue by Alexander-Barth** [gher-ulg/Diva-Workshops#11]
These notebooks are quite similar:

https://github.com/gher-ulg/Diva-Workshops/blob/master/notebooks/5-AdvancedTopics/18-defining-time-periods.ipynb

https://github.com/gher-ulg/Diva-Workshops/blob/master/notebooks/5-AdvancedTopics/time-aggregation.ipynb

If I am not mistaken, @ctroupin  will discuss them on Monday PM. Would it be useful to combine them?

**Comment by ctroupin** [comment]
Would make sense to merge them yes. 
Appending `time-aggregation.ipynb` at the end of `18-defining-time-periods.ipynb` for instance.

**Comment by Alexander-Barth** [comment]
I agree, that would be good.

**Comment by ctroupin** [comment]
Ok I've included all the cells from `time-aggregation.ipynb` into `18-defining-time-periods.ipynb` with some re-ordering. We can later remove `time-aggregation.ipynb`.
