### ISSUE TITLE
Remove NaN values

### ISSUE THREAD

**Issue by GeoTuxMan** [gher-ulg/Diva-Workshops#13]
Hi !

After I make an analysis, I got some warnings in output:
`
    dbinfo = diva3d((lonr,latr,depthr,TS),
              (lon,lat,depth,obstime),
              value,
              (lenx,leny,lenz2),
              0.1 * eps1 ./ diagR,
              filename,varname,
              bathname = bathname,
              bathisglobal = bathisglobal,
              plotres = plotres2,
              timeorigin = timeorigin,
              transform = Anam.loglin(slog),
              minfield = 0.,
              memtofit = 100,
              solver = :direct,
       )
    # Add used observations in the netcfd file
     DIVAnd.saveobs(filename,(lon,lat,depth,obstime),ids,used = dbinfo[:used])`

Output:
┌ Info: starting DIVA computations for Autumn
└ @ Main In[20]:12
┌ Info: 2020-01-29T11:35:36.05
└ @ Main In[20]:13
┌ Info: Will write results in /home/george/my_project_dir/DIN_Sel5_LCH_LCV_propuse_Autumn//Water_body_dissolved_inorganic_nitrogen_(DIN)_Autumn.4Danl.nc
└ @ Main In[20]:34
┌ Info: Creating netCDF file
└ @ DIVAnd /home/george/.julia/packages/DIVAnd/BGj1J/src/diva.jl:297
┌ Info: Time step 1 / 4
└ @ DIVAnd /home/george/.julia/packages/DIVAnd/BGj1J/src/diva.jl:333
┌ Warning: Observations equal to NaN: 3
└ @ DIVAnd /home/george/.julia/packages/DIVAnd/BGj1J/src/DIVAnd_obs.jl:45
┌ Info: number of windows: 11
└ @ DIVAnd /home/george/.julia/packages/DIVAnd/BGj1J/src/DIVAndgo.jl:89

So, I was wondering, if it's possible to remove all NaN values from dbinfo ( which is a dictionary) ?
Because, the resulting netcdf file, it's  almost full with NaN values.

Cheers !
George

**Comment by ctroupin** [comment]
Hello George,
can you give some more details: `dbinfo` is indeed a dictionary, so you mean you get lot of NaNs in the field `:residual`? Normally that should mean that many observations are not within the domain.

And in the netCDF are the NaNs in the analysis? Can you attach a plot of an analysis?

Thanks!

**Comment by GeoTuxMan** [comment]
Hi Charles,

Yes, the residual has many NaNs. And I want to remove them before the
observations is saved in netcdf
I attach a plot from Panoply

Cheers !

În mie., 29 ian. 2020 la 21:28, Charles Troupin <notifications@github.com>
a scris:

**Comment by jmbeckers** [comment]
Did you execute on all depth levels ? If you just tried the first levels a lot of observations will be outside of the grid

**Comment by GeoTuxMan** [comment]
The depth levels used:
depthr = collect(0.:2.5:60);

În mie., 29 ian. 2020 la 21:55, jmbeckers <notifications@github.com> a
scris:

**Comment by jmbeckers** [comment]
But the depth of the Black Sea  is  much higher. A data below 60 m will be considered "out of the domain" since you limit your grid at 60 m. If this is really what you want you can limit the data selection earlier by doing something like sel = sel .& (obsdepth .< 61)
But if your intention is to extend later the analysis to the bottom, just keep the data as they are
