### ISSUE TITLE
Horizontal correlation length fitting

### ISSUE THREAD

**Issue by ctroupin** [gher-ulg/Diva-Workshops#2]
In the previous version we were using
```julia
fithorzlen(x,v,z, nmean = 500, distbin = collect(0.:0.1:6))
```
to estimate the correlation length but the optional arguments `nmean` and `distbin` are not available anymore in [fit.jl](https://github.com/gher-ulg/DIVAnd.jl/blob/master/src/fit.jl#L976-L989), so what would be the equivalent call to `fithorzlen`?

Or we leave it as:
```julia
fithorzlen(x,v,z)
```

Same for 
```julia
lenz,infoz = fitvertlen(x,v,z, nmean = 500, distbin = collect([0.:50:400; 500:100:600]))
```

**Comment by Alexander-Barth** [comment]
This is great!
