### ISSUE TITLE
Writing a huge number of observations to a netCDF 

### ISSUE THREAD

**Issue by ctroupin** [gher-ulg/Diva-Workshops#4]
So I'm trying to write all the Atlantic observations inside the netCDF I've created with `DIVAnd`:
```julia
@show length(obslat);
length(obslat) = 31850848
DIVAnd.saveobs(filename,(obslon,obslat,obsdepth,obstime),obsid);
```
and the last command results in my browser to be *killed*. 

Probably this part has to be somehow enhanced.

**Comment by Alexander-Barth** [comment]
Could it be that you are out-of-memory? Does it work on the command line?

**Comment by ctroupin** [comment]
Will try. It's been a while so I don't remember.

**Comment by ctroupin** [comment]
Basically it's running the 91-Atlantic-Test. I re-tried and that was OK in command-line.
