### ISSUE TITLE
Notebook clean-up

### ISSUE THREAD

**Issue by Alexander-Barth** [gher-ulg/Diva-Workshops#6]
Are there any notebooks which are no longer be used (replaced e.g. by other functionalities)? If yes, I would propose to delete them.

**Comment by ctroupin** [comment]
In [https://github.com/gher-ulg/Diva-Workshops/blob/master/notebooks/1-Intro/02-Julia-introduction.ipynb](02-Julia-introduction.ipynb) there is now a section on netCDF (I think before we didn't have it) so the notebooks specifically dedicated to netCDF might be removed.

**Comment by ctroupin** [comment]
I did not see other notebooks to remove. 
There are some notebooks in `5-AdvancedTopics` that I don't really know (will see this morning).

Note that the directory `6-UnderConstruction` is meant to store the notebooks that are not 100% ready so probably you can skip this directory when testing with CI.

**Comment by ctroupin** [comment]
Still a few notebooks in "5-AdvancedTopics" I'm not sure what to do with:
* analysis-with-cycles.ipynb
* BigBlackSea.ipynb
* computing_analysis_datapoints.ipynb → do we keep it?
* HeatmapsCV.ipynb 
* Heatmaps.ipynb
* time-aggregation.ipynb → merged with 18-defining-time-periods.ipynb
