### ISSUE TITLE
Analysis notebook

### ISSUE THREAD

**Issue by ctroupin** [gher-ulg/Diva-Workshops#7]
In the previous version, we start making analysis with notebook [10-processing-quality-check.ipynb](https://github.com/gher-ulg/Diva-Workshops/blob/master/notebooks/3-Analysis/10-processing-quality-check.ipynb) which is about quality check.

I wonder if we should change the order, i.e., present QC based on the analysis later in the course.

**Comment by jmbeckers** [comment]
yes would be more natural and how it should be done (first a preliminary analysis and then finetuning)

**Comment by ctroupin** [comment]
OK, so 10-processing-quality-check.ipynb could be moved into the subdir 4-Postprocessing, what do you think @Alexander-Barth? 
Then we can add a `10-simple-analysis.ipynb`

**Comment by ctroupin** [comment]
In fact there is [`15-example-analysis.ipynb`](https://github.com/gher-ulg/Diva-Workshops/blob/master/notebooks/3-Analysis/15-example-analysis.ipynb), which explains how to use `diva3d`. This one, I think, should stay as and where it is, as it is already more complex than the simple analysis.

**Comment by Alexander-Barth** [comment]
OK, thanks, this is fine for me.
For your information, this is the code for testing the notebooks.
https://github.com/gher-ulg/Diva-Workshops/blob/master/utils/test-notebooks

It has some list of notebooks which are not tested (data file missing, too long,...). 
If some notebooks of this list needs to be renumbered, please change this file as well, if necessary.

**Comment by ctroupin** [comment]
Solution: we use the notebook `11-L-and-epsilon-effect.ipynb` (name can changed later) to explain what are the parameters used in a call of DIVAndrun, otherwise it's not really intuitive.
